version: '3'
services:
  zookeeper:
    container_name: zookeeper
    build: zookeeper/.
    ports: 
     - "2181:2181"
    network_mode: host
  kafka:
    container_name: kafka
    build: kafka/.
    ports:
     - "9092:9092"
    network_mode: host
    depends_on:
     - zookeeper
  kafka2:
    container_name: kafka2
    build: kafka2/.
    ports:
     - "9092:9092"
    network_mode: host
    depends_on:
     - kafka
  # mongo:
  #   container_name: mongo
  #   build: mongo/.
  #   ports:
  #     - "27017:27017"
  #   network_mode: host   
  spark:
    container_name: spark
    build: spark/.
    network_mode: host
    environment: 
      - SPARK_HOME=/home/user1/trabajoBDFI/spark-3.1.2-bin-hadoop2.7
    depends_on:
      - kafka2
  webflask:
    container_name: webflask
    build: webflask/.
    ports:
     - "5000:5000"
    network_mode: host
    environment: 
      - PROJECT_HOME=/app/practica_big_data_2019
    depends_on:
      - spark
    #  - mongo

